# HW 2: External Data, Visualization & Modular Code

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from src import utils

## Part 1: Load Data
Dataset: `mining-production.csv`

Sourced from: https://github.com/kadoa-org/world-mining-monitor

Download from: https://www.kadoa.com/mining/production

Acsessed Oct 17, 2026 12:34 pm

Saved in  data/external

In [2]:
# Read data in
data = pd.read_csv("../data/raw/mining-production.csv")
data.sample(10)

,company,operation,commodity,product_form,metric,period,value,unit,qoq_pct,country,...,source_document_name,source_page,source_section,source_table,source_row,source_column,source_excerpt,reported_value,reported_unit,reported_period
1892,Anglogold Ashanti,Sunrise Dam,gold,NaN,production,H1 2026,100.000,koz,NaN,NaN,...,anglogold-ashanti-1787060957590.pdf,14.0,Australia region,NaN,NaN,NaN,"Gold production was 100,000oz at a total cash ...","100,000",oz,H1 2026
9228,Aurubis,Pirdop,copper,cathode,production,9M FY2025 (Oct 2024-Jun 2025),169.000,kt,NaN,Bulgaria,...,Aurubis_Quarterly_20Report_Q3_2025_26.pdf,3.0,NaN,Aurubis Group production figures,Pirdop,9M 2024/25,"Pirdop | 1,000 t | 169",169,"1,000 t",9M 2024/25
9371,KGHM,NaN,silver,NaN,production,October 2023,3848.440,koz,NaN,NaN,...,kghm-oct-2024.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4293,Amman Mineral,NaN,copper,cathode,production,Q2 2025,19.170,kt,2918.9,NaN,...,amman-h1-2025.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5846,Glencore,"Australia (Mount Isa, Townsville, McArthur River)",lead,concentrate,production,H1 2025,67.600,kt,NaN,NaN,...,GLEN-2026-Half-Year-Report.pdf,20.0,Production Data,Production from own sources – Zinc assets,Lead in concentrates,H1 2025,Lead in concentrates kt 67.8 67.6 –,67.6,kt,H1 2025
221,Anglogold Ashanti,Iduapriem,gold,NaN,production,Q2 2026,47.000,koz,6.8,NaN,...,anglogold-ashanti-1787060957590.pdf,12.0,Africa region,NaN,NaN,NaN,"In Ghana, at Iduapriem, gold production was 47...","47,000",oz,Q2 2026
452,First Quantum Minerals,NaN,nickel,NaN,production,Q2 2026,11.246,kt,23.6,NaN,...,q2-2026-7df54829.pdf,5.0,CONSOLIDATED OPERATING HIGHLIGHTS,CONSOLIDATED OPERATING HIGHLIGHTS,Nickel production (contained tonnes),Three months ended June 30 2026,"Nickel production (contained tonnes) | 11,246","11,246",contained tonnes,Three months ended June 30 2026
4671,Gold Fields,NaN,gold,NaN,production,Q1 2025,568.600,koz,676.5,NaN,...,booklet-q1-2026.pdf,17.0,NaN,Ounces with metric tonnes and grade,– total,Total Mine operations,– total | Mar 2025 | 568.6,568.6,000 ounces,Mar 2025
2719,Norsk Hydro,Metal Markets,aluminium,recycled,production,Q4 2025,181.000,kt,4.0,NaN,...,norskhydro-q1-2026.pdf,14.0,Performance,Hydro Metal Markets financial and operational ...,Recycling production (kmt),Fourth quarter 2025,Recycling production (kmt) | 181,181,kmt,Fourth quarter 2025
4120,Rio Tinto,NaN,silver,refined,production,Q2 2025,509.000,koz,-97.3,NaN,...,2026-first-qor.pdf,20.0,Rio Tinto production summary,Rio Tinto share of production,Silver - refined,Q2 2025,Silver - refined ('000 oz) 635 509 254 439 632,509,'000 oz,Q2 2025

In [3]:
#inspect shape, columns, dtypes, and missingness
print(f"Shape: {data.shape}\n")
print(f"Columns: {data.columns}\n")

Shape: (9410, 22)

Columns: Index(['company', 'operation', 'commodity', 'product_form', 'metric', 'period',
       'value', 'unit', 'qoq_pct', 'country', 'basis', 'source_url',
       'source_document_name', 'source_page', 'source_section', 'source_table',
       'source_row', 'source_column', 'source_excerpt', 'reported_value',
       'reported_unit', 'reported_period'],
      dtype='str')

In [4]:
# Inspect data types
print(f"Dtypes: \n{data.dtypes}\n")

Dtypes:
company                     str
operation                   str
commodity                   str
product_form                str
metric                      str
period                      str
value                   float64
unit                        str
qoq_pct                 float64
country                     str
basis                       str
source_url                  str
source_document_name        str
source_page             float64
source_section              str
source_table                str
source_row                  str
source_column               str
source_excerpt              str
reported_value              str
reported_unit               str
reported_period             str
dtype: object

In [5]:
# List of columns with the amount missing, sorted by value
print(f"Missingness: \n{data.isna().sum().sort_values()}\n")

Missingness:
company                    0
commodity                  0
period                     0
metric                     0
basis                      0
source_url               302
source_document_name     302
value                    357
unit                     357
operation               2570
source_excerpt          3835
reported_value          3835
reported_unit           3835
reported_period         3835
source_section          4028
source_page             4099
source_row              4204
source_column           4261
source_table            4399
product_form            5181
qoq_pct                 5207
country                 6865
dtype: int64

In [6]:
# Proportion missing
print(f"Missingness Proportion out of {len(data)} rows: \n{round((data.isna().sum()/len(data)*100).sort_values(), 3)}%\n")

Missingness Proportion out of 9410 rows:
company                  0.000
commodity                0.000
period                   0.000
metric                   0.000
basis                    0.000
source_url               3.209
source_document_name     3.209
value                    3.794
unit                     3.794
operation               27.311
source_excerpt          40.755
reported_value          40.755
reported_unit           40.755
reported_period         40.755
source_section          42.806
source_page             43.560
source_row              44.676
source_column           45.282
source_table            46.748
product_form            55.058
qoq_pct                 55.335
country                 72.954
dtype: float64%

### Part 3 — Exploratory analysis

Answer at least two data questions.


Use appropriate summaries such as:
* counts;
* means/medians;
* grouped summaries;
* distributions;
* associations.

Explain the substantive meaning of the results.

#### Questions:
1. How much of each commodity is produced in total each quarter? (Grouped Summary)
2. How many companies mine each commodity? What is the distribution of number of commodities mined per company?

### Question 1: How much of each commodity is produced in total each quarter?

Requires that the units and times are homogenized.
Returns 595 totals, so a peek at the max (most mined commodity the 7 year period) is more interesting.

In [ ]:
data["unit"].value_counts() # Convert these all to kg

1624

In [16]:
data_homogenized_units = utils.apply_extraction_units(data, "kg_mined", "unit", "value")

data_homogenized_units[["commodity", "kg_mined", "unit", "value"]].sample(5)

      commodity      kg_mined unit    value
5849       zinc  1.520000e+07   kt   15.200
1019  aluminium  1.820700e+07   kt   18.207
8751     silver  2.799313e+04  koz  900.000
2290       gold  1.195300e+04  koz  384.298
9366        pgm           NaN  NaN      NaN

In [9]:
data["period"].value_counts() # 82 different time periods over 7 years x 4 quarters

period
Q1 2026                          937
Q1 2025                          811
Q2 2026                          790
Q4 2025                          695
Q2 2025                          685
                                ...
Annual Average                     3
9M FY2026                          3
9M FY2024 (Oct 2023-Jun 2024)      2
HY2026 (Jul-Dec 2025)              2
H1 FY2025                          2
Name: count, Length: 82, dtype: int64

In [20]:
time_and_kg_homogenized = utils.homogenize_time_periods_and_split_values(data_homogenized_units, "period", value_cols=["value"])

print(f"Data Length before: {len(data)}\nData Length after: {len(time_and_kg_homogenized)}")

Data Length before: 9410
Data Length after: 14788

In [21]:
time_and_kg_homogenized["quarter"].value_counts() # now we have 28 different values

quarter
Q1 2025    2221
Q2 2025    2071
Q1 2026    1748
Q2 2026    1550
Q3 2025    1356
Q4 2025    1312
Q1 2024     915
Q2 2024     834
Q3 2024     623
Q4 2024     581
Q2 2023     224
Q1 2023     220
Q3 2023     148
Q4 2023     123
Q3 2026     104
Q4 2022      76
Q3 2022      70
Q2 2022      65
Q4 2021      62
Q1 2022      60
Q4 2026      59
Q3 2021      57
Q2 2021      57
Q1 2021      52
Q4 2020      50
Q3 2020      50
Q2 2020      50
Q1 2020      50
Name: count, dtype: int64

In [42]:
# keep only necessary columns
processed_data_question_1 = time_and_kg_homogenized[["commodity", "kg_mined", "quarter"]]

# create grouped summary
processed_data_question_1.groupby(["commodity", "quarter"])["kg_mined"].sum()

commodity  quarter
3e pgm     Q1 2025    0.000000e+00
alumina    Q1 2023    1.894600e+10
           Q1 2024    4.709520e+10
           Q1 2025    7.868840e+10
           Q1 2026    3.837339e+10
                          ...
zircon     Q1 2025    8.600000e+07
           Q1 2026    2.400000e+07
           Q2 2024    3.200000e+07
           Q2 2025    8.900000e+07
           Q2 2026    1.200000e+07
Name: kg_mined, Length: 595, dtype: float64

In [41]:
# Check the total amount mined per commodity in decreasing order for fun
commodity_totals = (
    processed_data_question_1.groupby("commodity")["kg_mined"].sum()
    .sort_values(ascending=False)
)

commodity_totals

commodity
iron ore                       2.055913e+13
coal                           3.726021e+12
bauxite                        1.685218e+12
alumina                        6.555345e+11
copper                         6.139946e+11
aluminium                      4.352164e+11
nickel                         4.246465e+11
thermal coal                   3.247000e+11
zinc                           2.471545e+11
manganese                      1.916740e+11
phosphate                      1.061875e+11
chromite                       3.006500e+10
lead                           2.734794e+10
mineral_sands                  2.013700e+10
mined metal                    2.002800e+10
refined metal                  1.693800e+10
semi-soft coking coal          1.210000e+10
pig iron                       8.798000e+09
chrome                         8.127000e+09
titanium_dioxide               6.353000e+09
saleable metal                 3.872000e+09
cobalt                         3.039448e+09
molybdenum                     2.721981e+09
ilmenite                       2.391000e+09
lithium                        8.603200e+08
zinc + lead                    7.308280e+08
nickel pig iron                5.870870e+08
steel dust                     5.573300e+08
silver                         3.427623e+08
zircon                         2.750000e+08
niobium                        2.301360e+08
lead alloys                    2.167120e+08
salt slags and spl             2.092530e+08
tungsten                       1.950880e+08
uranium                        1.270480e+08
zinc clinker                   1.131440e+08
gold                           2.252764e+07
lithium hydroxide              5.500000e+06
pgm                            3.009525e+06
nickel sulfate                 3.600000e+04
diamonds                       2.113400e+04
gold doré                      5.690412e+03
magnetite                      0.000000e+00
magnesium sulphate             0.000000e+00
limonite                       0.000000e+00
liquid sulphur dioxide         0.000000e+00
ferro chrome                   0.000000e+00
3e pgm                         0.000000e+00
ammonium sulphate              0.000000e+00
ammonium bisulphite            0.000000e+00
rhodium                        0.000000e+00
precious metals concentrate    0.000000e+00
oil and gas                    0.000000e+00
saprolite                      0.000000e+00
sulphur concentrate            0.000000e+00
sodium sulphate                0.000000e+00
vanadium pentoxide             0.000000e+00
vanadium                       0.000000e+00
Name: kg_mined, dtype: float64

### Question 2: How many companies mine each commodity? What is the distribution of number of commodities mined per company?

In [50]:
q2_data = time_and_kg_homogenized[["commodity", "kg_mined", "company"]]

# Check missingness
q2_data.isna().sum()

commodity      0
kg_mined     579
company        0
dtype: int64

In [53]:
#fill zeroes for missing values
q2_data_filledna = q2_data.fillna(0)
q2_data_filledna.isna().sum()

commodity    0
kg_mined     0
company      0
dtype: int64

In [64]:
# a: How many companies mine each commodity?
q2_data_filledna.groupby("commodity")["company"].count().sort_values(ascending= False)

commodity
copper                         3515
gold                           2868
silver                         1630
zinc                           1486
lead                            858
aluminium                       736
nickel                          635
molybdenum                      502
pgm                             403
iron ore                        396
alumina                         257
coal                            230
cobalt                          199
bauxite                         141
manganese                       119
lithium                         102
chromite                         74
phosphate                        71
uranium                          63
thermal coal                     50
mineral_sands                    46
diamonds                         43
tungsten                         41
niobium                          33
mined metal                      32
refined metal                    25
pig iron                         21
liquid sulphur dioxide           14
precious metals concentrate      13
gold doré                        13
titanium_dioxide                 12
zircon                           12
ilmenite                         12
oil and gas                      11
saleable metal                   11
ammonium bisulphite              10
ammonium sulphate                10
semi-soft coking coal            10
sodium sulphate                  10
magnesium sulphate               10
chrome                            9
nickel pig iron                   6
lead alloys                       5
limonite                          5
saprolite                         5
ferro chrome                      4
zinc clinker                      4
vanadium pentoxide                4
zinc + lead                       4
rhodium                           4
magnetite                         3
sulphur concentrate               2
salt slags and spl                2
nickel sulfate                    2
steel dust                        2
3e pgm                            1
lithium hydroxide                 1
vanadium                          1
Name: company, dtype: int64

In [ ]:
# b: How many commodities are mined on average per company?

### Part 4 — Visualization

Create at least three plots:

1. one distribution plot;
2. one comparison across groups;
3. one relationship plot.

The figures must include:
* meaningful title;
* axis labels;
* units where appropriate;
* readable legend;
* short caption explaining the conclusion.